import { useState } from "react";
import { Check, Save } from "lucide-react";
import { ALLERGENS, ALLERGEN_LABEL, CATEGORY_LABEL, dishName } from "../lib/format";
import type { Allergen, Dish } from "../types";
import { Sheet } from "./Sheet";

export function DishEditor({ dish, onSave, onClose }: { dish?: Dish; onSave: (d: Dish) => void; onClose: () => void }) {
  const [draft, setDraft] = useState<Dish>(dish ?? { id: `dish_${crypto.randomUUID()}`, name_en: "", price: null, category: "other", spice_level: 0, portion: "medium", main_ingredients: [], allergens: [], is_vegetarian: null, is_vegan: null, contains_pork: null, contains_beef: null, confirm_with_staff: [] });
  const [ingredients, setIngredients] = useState(dish?.main_ingredients.map(i => i.name).join(", ") ?? "");
  const [questions, setQuestions] = useState(dish?.confirm_with_staff.join("\n") ?? "");
  const set = (key: keyof Dish, value: unknown) => setDraft(prev => ({ ...prev, [key]: value }));
  const toggleAllergen = (a: Allergen) => set("allergens", draft.allergens.some(f => f.allergen === a) ? draft.allergens.filter(f => f.allergen !== a) : [...draft.allergens, { allergen: a, tier: "menu", confidence: 1, reason: "Recorded by the menu reviewer." }]);
  return <Sheet title={dish ? `Edit ${dishName(dish)}` : "Add a dish"} onClose={onClose}><form className="editor-form" onSubmit={e => { e.preventDefault(); onSave({ ...draft, name_en: draft.name_en?.trim(), main_ingredients: ingredients.split(",").map(s => s.trim()).filter(Boolean).map(name => draft.main_ingredients.find(i => i.name === name) ?? { name, tier: "menu" }), confirm_with_staff: questions.split("\n").map(s => s.trim()).filter(Boolean) }); }}>
    <label className="field-label">English dish name<input className="field" required value={draft.name_en ?? ""} onChange={e => set("name_en", e.target.value)}/></label>
    <div className="field-grid"><label className="field-label">Menu price<input className="field" required type="number" min="0" step="0.01" value={draft.price ?? ""} onChange={e => set("price", e.target.value === "" ? null : Number(e.target.value))}/></label><label className="field-label">Category<select className="field" value={draft.category} onChange={e => set("category", e.target.value)}>{Object.entries(CATEGORY_LABEL).map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select></label></div>
    <div className="field-grid"><label className="field-label">Spice level<select className="field" value={draft.spice_level} onChange={e => set("spice_level", Number(e.target.value))}>{["No heat", "Mild", "Medium", "Hot"].map((s, i) => <option key={i} value={i}>{s}</option>)}</select></label><label className="field-label">Portion<select className="field" value={draft.portion} onChange={e => set("portion", e.target.value)}>{["individual", "small", "medium", "large", "shared"].map(s => <option key={s} value={s}>{s}</option>)}</select></label></div>
    <label className="field-label">Ingredients listed on the menu<input className="field" value={ingredients} onChange={e => setIngredients(e.target.value)} placeholder="Tofu, mushrooms, garlic"/><small>Separate with commas. Leave unknown ingredients blank.</small></label>
    <div className="field-label">Recorded allergens</div><div className="editor-chips">{ALLERGENS.map(a => <button key={a} type="button" aria-pressed={draft.allergens.some(f => f.allergen === a)} className={draft.allergens.some(f => f.allergen === a) ? "selected" : ""} onClick={() => toggleAllergen(a)}>{draft.allergens.some(f => f.allergen === a) && <Check size={11}/>} {ALLERGEN_LABEL[a]}</button>)}</div><p className="helper">Unselected allergens mean no recorded evidence, not confirmed absence.</p>
    <div className="field-grid">{([['is_vegetarian', 'Vegetarian'], ['is_vegan', 'Vegan'], ['contains_pork', 'Contains pork'], ['contains_beef', 'Contains beef']] as const).map(([key, label]) => <label className="field-label" key={key}>{label}<select className="field" value={draft[key] === null ? "unknown" : String(draft[key])} onChange={e => set(key, e.target.value === "unknown" ? null : e.target.value === "true")}><option value="unknown">Unknown / ask staff</option><option value="true">Yes</option><option value="false">No</option></select></label>)}</div>
    <label className="field-label">Questions for staff<textarea className="field" rows={3} value={questions} onChange={e => setQuestions(e.target.value)} placeholder="One question per line"/></label>
    <button className="btn btn-primary w-full" type="submit" disabled={!draft.name_en?.trim() || draft.price == null}><Save size={16}/>Save dish for review</button>
  </form></Sheet>;
}
